### ISSUE TITLE
UIGraphicsGetCurrentContext is Nil

### ISSUE THREAD

**Issue by yehiabairm** [claudot/Swift-UIImageView-Letters#3]
I got crash in using let context = UIGraphicsGetCurrentContext() as it returns nil !

**Comment by oleghnidets** [comment]
@yehiabairm Is it reproducible in sample project?

**Comment by oleghnidets** [comment]
Could you, please, provide more details?

**Comment by mrhaxic** [comment]
Replace `context!` to `context?`

**Comment by oleghnidets** [comment]
https://github.com/claudot/Swift-UIImageView-Letters/releases/tag/2.1.0
