### ISSUE TITLE
Pod install is broken

### ISSUE THREAD

**Issue by bpappin** [claudot/Swift-UIImageView-Letters#4]
This is in a project recently converted to swift 4.

`Installing Letters (1.0.2)

[!] Error installing Letters
[!] /usr/bin/git clone https://github.com/claudot/Swift-UIImageView-Letters.git /var/folders/j6/1l48hrvn7678cpk07bqn7zzh0000gn/T/d20171031-73882-1vdn6gz --template= --single-branch --depth 1 --branch 1.0.2

Cloning into '/var/folders/j6/1l48hrvn7678cpk07bqn7zzh0000gn/T/d20171031-73882-1vdn6gz'...
warning: Could not find remote branch 1.0.2 to clone.
fatal: Remote branch 1.0.2 not found in upstream origin
`

**Comment by oleghnidets** [comment]
My fault. [Check it out](https://github.com/claudot/Swift-UIImageView-Letters/releases/tag/1.0.2).
I forgot that someone can still use Swift 3 😬
