### ISSUE TITLE
Use of undeclared identifier NSAttributedStringKey

### ISSUE THREAD

**Issue by maninp** [claudot/Swift-UIImageView-Letters#5]
I'm getting this error on Xcode 8.3.3, Swift 3. 

![screen shot 2017-11-03 at 6 40 42 pm](https://user-images.githubusercontent.com/7687090/32375193-b5f1a880-c0c6-11e7-9c3f-a2b5d8f89662.png)

**Comment by oleghnidets** [comment]
Because the library doesn't support Swift 3 anymore. If you want to support Swift 3, please, use https://github.com/claudot/Swift-UIImageView-Letters/releases/tag/1.0.2 


`pod 'Alamofire', :git => 'https://github.com/claudot/Swift-UIImageView-Letters.git', :tag => '1.0.2' `

**Comment by maninp** [comment]
I don't want back to older version. Because the current code is much cleaner than old. So I just modify the code(ie just copied the logic from old code).
