### ISSUE TITLE
Type 'NSAttributedStringKey' (aka 'NSString') has no member 'foregroundColor'

### ISSUE THREAD

**Issue by tylerjames** [claudot/Swift-UIImageView-Letters#7]
Is this library only compatible with Swift 4?

**Comment by oleghnidets** [comment]
Yes, only Swift 4 supported. 

If you want to use Swift 3, please, use https://github.com/claudot/Swift-UIImageView-Letters/releases/tag/1.0.2 

`pod 'Alamofire', :git => 'https://github.com/claudot/Swift-UIImageView-Letters.git', :tag => '1.0.2' `

**Comment by korantengNanaYaw** [comment]
pod Alamorefire ?,im confused .
