### ISSUE TITLE
i error when building project 

### ISSUE THREAD

**Issue by amrangry** [claudot/Swift-UIImageView-Letters#9]
the following error is shown when i try to build the project

i use Xcode 9 with swift version 3.2 

Type 'NSAttributedStringKey' (aka 'NSString') has no member 'foregroundColor'

**Comment by oleghnidets** [comment]
If you want to use Swift 3, please, use https://github.com/claudot/Swift-UIImageView-Letters/releases/tag/1.0.2

pod 'Letters', :git => 'https://github.com/claudot/Swift-UIImageView-Letters.git', :tag => '1.0.2'
